version: 2
updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 5
    directory: /
    schedule:
      interval: monthly
    allow:
      - dependency-type: production
    commit-message:
      prefix: build
