name: CICD

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile --prefer-offline

      - run: yarn lint

      - run: yarn check-types

      - run: yarn test

      - run: yarn build
