name: CICD

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # required to get all history, not just commit that triggers current run
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v2
        with:
          configFile: commitlint.config.js

  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile --prefer-offline

      - run: yarn lint

      - run: yarn check-types

      - run: yarn test

      - run: yarn build
