name: Documentation

on:
  pull_request:

jobs:
  # check links are valid
  check-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        check-modified-files-only: yes
        use-quiet-mode: yes
        config-file: '.md-link-check.config.json'
        base-branch: main
